# Dockerfile.rabbitmq
FROM rabbitmq:latest

RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.2.0/rabbitmq_delayed_message_exchange-4.2.0.ez -P /plugins
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange