FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0

RUN go build -o main ./cmd/main.go 

FROM alpine:latest 

RUN apk --no-cache add ca-certificates

COPY --from=builder ./app/main ./main

EXPOSE 8080

CMD ["./main"]